name: Generate Snake

on:
  # Läuft automatisch alle 12 Stunden
  schedule:
    - cron: "0 */12 * * *"
  
  # Ermöglicht das manuelle Starten über den GitHub-Tab "Actions"
  workflow_dispatch:
  
  # Läuft auch bei jedem Push auf das main-Repository
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # 1. Repository auschecken
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Snake-Animation generieren
      - name: Generate the snake svg files
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: MusawarQaderi
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # 3. Änderungen in den branch "output" pushen (damit dein README darauf zugreifen kann)
      - name: Push snake to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
